# Dependencies
markdown:         kramdown

gems: 			  [jekyll-paginate, jekyll-gist]

# Setup
title:            Web / Tech / Beer
tagline:          'some tagline'
description:      'Web technologies, code, server applications, beer, etc'
url:              http://fridgerator.github.io

author:
  name:           'Nick Franken'
  url:            https://twitter.com/fridgamarator

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/fridgerator
